# Generated by Django 4.1.7 on 2023-08-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts_videos')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
